SET C51INC=d:\Keil\C51\Inc
SET C51LIB=d:\Keil\C51\Lib
SET CPU_TYPE=STC12C5628AD
SET CPU_VENDOR=STC
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x02AEA540
"d:\Keil\C51\BIN\A51.EXE" @.\outPut\STARTUP._ia
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\uart.__i
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\ep9142.__i
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\sii9135.__i
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\main.__i
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\COMMON~1.__I
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\rxConf.__i
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\SIIRX_~1.__I
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\SiITrace.__i
"d:\Keil\C51\BIN\C51.EXE" @.\outPut\SIISYS~1.__I
"d:\Keil\C51\BIN\BL51.EXE" @.\outPut\HDMI2S~1.LNP
"d:\Keil\C51\BIN\OH51.EXE" ".\outPut\HDMI2SDI-box-v10" 
